### ISSUE TITLE
Graph Explorer compilation error

### ISSUE THREAD

**Issue by a2chisperfect** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#19]
I installed Node.js using the link in the readme, then run "npm install" command. When i'm trying to compile Graph Explorer project i gotta compilation error. Any help would be appreciated.
![error](https://user-images.githubusercontent.com/34550531/37878560-a69fee92-3073-11e8-8fbe-79b40552f0a5.jpg)

**Comment by alexdrenea** [comment]
I am using  Node v8.1.2 and npm v5.0.3 and everything works.
I remember some time ago, I ran into similar issues until I updated my tool chain. 

Can you check what versions you currenty have (npm --version and node --version) and then update to the versions I mentioned see if it fixes your issues?

**Comment by philemon33** [comment]
I installed the latest node 8.10.0 and npm 5.6.0, and get the same error.

**Comment by philemon33** [comment]
I actually got it working with aurelia-binding 1.2.1. Still have a problem with the actual web app. Investigating...

**Comment by alexdrenea** [comment]
Good to know that 1.2.1 works.
What other problems are you encountering?

**Comment by camigira** [comment]
Working after adding `"aurelia-binding": "1.0.0",` in package.json

thanks!

**Comment by philemon33** [comment]
@alexdrenea, problems with the type of CosmossDB  I created I believe. I created a Gremlin Graph, and the GraphExplorer cannot talk to that type of DB. Still looking into that.

**Comment by alexdrenea** [comment]
@philemon33 that seems to be a different issue (although, GraphExplorer works specifically with CosmosDB Graph collections so i think you created the right one) - I would like to close this issue and you can create a separate one for the connection issue you mentioned?

**Comment by philemon33** [comment]
Fine with me, Not sure https://github.com/a2chisperfect got his resolution though.

**Comment by a2chisperfect** [comment]
alexdrenea, your solution really works). Thank you !
